import { relative } from "node:path";

function mark(value) {
  return value ? "PASS" : "FAIL";
}

function duration(ms) {
  if (ms < 1_000) return `${ms}ms`;
  if (ms < 60_000) return `${(ms / 1_000).toFixed(1)}s`;
  return `${(ms / 60_000).toFixed(1)}m`;
}

function ranked(results) {
  return [...results].sort((a, b) => Number(b.passed) - Number(a.passed) || a.agent.durationMs - b.agent.durationMs);
}

function changeCount(run) {
  if (!run.changes?.available) return "patch unavailable";
  return `${run.changes.filesChanged} file${run.changes.filesChanged === 1 ? "" : "s"}`;
}

export function renderMarkdownReport(result) {
  const rows = ranked(result.results).map((run, index) =>
    `| ${index + 1} | ${run.agentId} | ${run.repetition} | ${mark(run.passed)} | ${duration(run.agent.durationMs)} | ${run.checks.filter((check) => check.passed).length}/${run.checks.length} |`
  );
  const details = result.results.flatMap((run) => [
    `### ${run.agentId} / run ${run.repetition}`,
    "",
    `- Result: **${mark(run.passed)}**`,
    `- Agent exit: ${run.agent.code ?? "spawn error"}${run.agent.timedOut ? " (timed out)" : ""}`,
    `- Agent time: ${duration(run.agent.durationMs)}`,
    `- Changes: ${run.changes?.available ? `${changeCount(run)}, +${run.changes.insertions}/-${run.changes.deletions}` : "unavailable"}`,
    ...run.checks.map((check) => `- ${check.name}: ${mark(check.passed)} (${duration(check.durationMs)})`),
    ""
  ]);
  return [
    `# RepoRace: ${result.task.title}`,
    "",
    `Task: \`${result.task.id}\`  `,
    `Started: ${result.startedAt}  `,
    `Passing runs: ${result.summary.passed}/${result.summary.total}`,
    "",
    "| Rank | Agent | Run | Result | Agent time | Checks |",
    "| ---: | --- | ---: | --- | ---: | ---: |",
    ...rows,
    "",
    "## Run details",
    "",
    ...details,
    "Generated by [RepoRace](https://github.com/Dyltom/reporace)."
  ].join("\n");
}

function escapeHtml(value) {
  return String(value).replace(/[&<>\"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#039;" })[character]);
}

export function renderHtmlReport(result) {
  const cards = ranked(result.results).map((run, index) => `
    <article class="card ${run.passed ? "pass" : "fail"}">
      <div class="rank">#${index + 1}</div>
      <div><h2>${escapeHtml(run.agentId)}</h2><p>Run ${run.repetition} · ${duration(run.agent.durationMs)} · ${changeCount(run)} changed</p></div>
      <strong>${mark(run.passed)}</strong>
      <ul>${run.checks.map((check) => `<li><span>${escapeHtml(check.name)}</span><b>${mark(check.passed)}</b></li>`).join("")}</ul>
    </article>`).join("");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>RepoRace · ${escapeHtml(result.task.title)}</title>
<style>
:root{color-scheme:dark;--ink:#f5f4ef;--muted:#aaa9a3;--panel:#171815;--line:#33352e;--lime:#c9ff54;--red:#ff6b6b}*{box-sizing:border-box}body{margin:0;background:#0d0e0c;color:var(--ink);font:16px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}main{width:min(980px,calc(100% - 32px));margin:64px auto}header{border-bottom:1px solid var(--line);padding-bottom:32px;margin-bottom:24px}.eyebrow{color:var(--lime);letter-spacing:.16em;text-transform:uppercase;font-weight:700}h1{font:clamp(2.3rem,7vw,5.4rem)/.95 system-ui,sans-serif;margin:.25em 0;max-width:14ch}.summary{color:var(--muted)}.grid{display:grid;gap:14px}.card{display:grid;grid-template-columns:54px 1fr auto;gap:18px;align-items:center;background:var(--panel);border:1px solid var(--line);border-left:4px solid var(--red);padding:20px}.card.pass{border-left-color:var(--lime)}.card h2,.card p{margin:0}.card p{color:var(--muted)}.card>strong{color:var(--red)}.card.pass>strong{color:var(--lime)}.rank{font-size:1.4rem;color:var(--muted)}ul{grid-column:2/-1;list-style:none;padding:12px 0 0;margin:0;border-top:1px solid var(--line)}li{display:flex;justify-content:space-between;padding:4px 0}li b{font-size:.8rem}footer{color:var(--muted);margin-top:32px}a{color:var(--lime)}@media(max-width:600px){main{margin:32px auto}.card{grid-template-columns:38px 1fr}.card>strong{grid-column:2}.card ul{grid-column:1/-1}}
</style></head><body><main><header><div class="eyebrow">RepoRace / deterministic agent eval</div><h1>${escapeHtml(result.task.title)}</h1><p class="summary">${result.summary.passed} of ${result.summary.total} runs passed · ${escapeHtml(result.task.id)} · ${escapeHtml(result.startedAt)}</p></header><section class="grid">${cards}</section><footer>Same task. Isolated workspaces. Checks decide. <a href="https://github.com/Dyltom/reporace">RepoRace</a>.</footer></main></body></html>`;
}

export function consoleSummary(result) {
  const lines = ["", `RepoRace · ${result.task.title}`, ""];
  for (const run of ranked(result.results)) {
    lines.push(`${mark(run.passed).padEnd(4)}  ${run.agentId.padEnd(16)} run ${run.repetition}  ${duration(run.agent.durationMs).padStart(7)}  ${run.checks.filter((check) => check.passed).length}/${run.checks.length} checks  ${changeCount(run)}`);
  }
  lines.push("", `${result.summary.passed}/${result.summary.total} runs passed`, `Report: ${relative(process.cwd(), result.reportPaths.html) || result.reportPaths.html}`, "");
  return lines.join("\n");
}
